# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Traal
tagline:          ''
description:      'Michał "spitfire" Borejszo'
url:              http://blog.traal.eu
#baseurl:          /

author:
  name:           'Michal Borejszo'

paginate:         5

# Custom vars
version:          2.1.0
repository:           spitfire05/spitfire05.github.io
